import { Helpers } from '../../../../helpers'

export class CodesOptions {

    data: any;

    constructor(token,user) {
        this.data = {
            data: {
                type: 'remote',
                source: {
                    read: {
                        url: `${Helpers.apiUrl}codes`,
                        method: 'GET',
                        params: {
                            query: {
                                
                            }
                        },
                        headers: {
                            'Authorization': `Bearer ${token}`
                        }
                    }
                },

                pageSize: 10,
                saveState: {
                    cookie: false,
                    webstorage: false
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            layout: {
                theme: 'default', // datatable theme
                class: 'm-datatable--brand', // custom wrapper class
                scroll: false, // enable/disable datatable scroll both horizontal and vertical when needed.
                footer: false // display/hide footer
            },
            sortable: true,
            pagination: true,
            search: {
                // search delay in milliseconds
                delay: 200,
                // input text for search
                input: $('#generalSearch'),
            },
            columns: [
                {
                    field: 'id',
                    title: '#',
                    sortable: false, // disable sort for this column
                    width: 40,
                    textAlign: 'center',
                    selector: { class: 'm-checkbox--solid m-checkbox--brand' },
                }, {
                    field: "code",
                    title: "Code",
                }, {
                    field: "generatedBy",
                    title: "Generated By",
                    template: function(row){
                        let fname ='';
                        let lname = '';
                        if(row.generatedBy){
                            fname = row.generatedBy.firstName;
                            lname = row.generatedBy.lastName;
                        }
                        return fname +' '+ lname;
                    }
                }, {
                    field: "usedBy",
                    title: "Used By",
                    template: function(row){
                        let fname ='';
                        let lname = '';
                        if(row.usedBy){
                            fname = row.usedBy.firstName;
                            lname = row.usedBy.lastName;
                        }
                        return fname +' '+ lname;
                    }
                }, {
                    field: "status",
                    title: "Status",
                    width: 150
                }
            ]
        }
    }

}